name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/border-radius/
            rm -rf /home/cloned-repo-border-radius/
            cd /var/www
            mkdir border-radius
            cd /home
            mkdir cloned-repo-border-radius
            cd cloned-repo-border-radius
            git clone https://github.com/Andrii-Yukhymenko/border-radius-constructor.git
            cd border-radius-constructor/
            cp -r app/* /var/www/border-radius
